MEDICINES = {
    "Fungal infection": ["Clotrimazole", "Fluconazole", "Terbinafine"],
    "Allergy": ["Cetirizine", "Loratadine", "Diphenhydramine"],
    "GERD": ["Omeprazole", "Ranitidine", "Antacids"],
    "Diabetes": ["Metformin", "Insulin", "Glipizide"],
    "Hypertension": ["Amlodipine", "Lisinopril", "Losartan"],
    "Migraine": ["Ibuprofen", "Sumatriptan", "Paracetamol"],
    "Malaria": ["Chloroquine", "Artemether", "Primaquine"],
    "Dengue": ["Paracetamol", "ORS", "Rest"],
    "Typhoid": ["Ciprofloxacin", "Azithromycin", "Ceftriaxone"],
    "Common Cold": ["Paracetamol", "Antihistamine", "Vitamin C"],
    "Pneumonia": ["Amoxicillin", "Azithromycin", "Levofloxacin"],
    "Tuberculosis": ["Isoniazid", "Rifampin", "Pyrazinamide"],
    "Arthritis": ["Ibuprofen", "Naproxen", "Methotrexate"],
    "Gastroenteritis": ["ORS", "Zinc tablets", "Metronidazole"],
    "Jaundice": ["Liv 52", "Rest", "IV fluids"],
    "Chicken pox": ["Acyclovir", "Calamine lotion", "Paracetamol"],
    "Hepatitis B": ["Tenofovir", "Entecavir", "Interferon"],
    "Hepatitis C": ["Sofosbuvir", "Ribavirin", "Daclatasvir"],
    "Urinary tract infection": ["Nitrofurantoin", "Trimethoprim", "Ciprofloxacin"],
    "Psoriasis": ["Methotrexate", "Cyclosporine", "Coal tar"],
    "Impetigo": ["Mupirocin", "Amoxicillin", "Cephalexin"],
    "Acne": ["Benzoyl peroxide", "Clindamycin", "Tretinoin"],
    "Bronchial Asthma": ["Salbutamol", "Budesonide", "Montelukast"],
    "Hypertension": ["Amlodipine", "Atenolol", "Losartan"],
    "Cervical spondylosis": ["Ibuprofen", "Diclofenac", "Physiotherapy"],
    "Paralysis (brain hemorrhage)": ["Aspirin", "Warfarin", "Physiotherapy"],
    "Jaundice": ["Liv 52", "Silymarin", "Rest"],
    "Malaria": ["Chloroquine", "Artemether", "Doxycycline"],
    "Chicken pox": ["Acyclovir", "Calamine", "Paracetamol"],
    "Dengue": ["Paracetamol", "ORS", "Platelet transfusion"],
    "Drug Reaction": ["Stop medication", "Antihistamine", "Steroids"],
    "Peptic ulcer disease": ["Omeprazole", "Amoxicillin", "Clarithromycin"],
    "AIDS": ["Antiretroviral therapy", "Cotrimoxazole", "Fluconazole"],
    "Diabetes": ["Metformin", "Insulin", "Sitagliptin"],
    "Gastroenteritis": ["ORS", "Zinc", "Metronidazole"],
    "Bronchial Asthma": ["Salbutamol", "Ipratropium", "Prednisolone"],
    "Hypertension": ["Amlodipine", "Lisinopril", "Hydrochlorothiazide"],
    "Migraine": ["Sumatriptan", "Topiramate", "Amitriptyline"],
    "Cervical spondylosis": ["Ibuprofen", "Muscle relaxants", "Physiotherapy"],
    "Heart attack": ["Aspirin", "Nitroglycerin", "Call emergency"],
    "Varicose veins": ["Compression stockings", "Sclerotherapy", "Surgery"],
    "Hypothyroidism": ["Levothyroxine", "Liothyronine", "Iodine supplements"],
    "Hyperthyroidism": ["Methimazole", "Propylthiouracil", "Beta blockers"],
    "Hypoglycemia": ["Glucose tablets", "Fruit juice", "Glucagon injection"],
    "Osteoarthritis": ["Paracetamol", "Ibuprofen", "Glucosamine"],
    "Alcoholic hepatitis": ["Corticosteroids", "Pentoxifylline", "Abstinence"],
    "Tuberculosis": ["Isoniazid", "Rifampicin", "Ethambutol"],
    "Common Cold": ["Paracetamol", "Cetirizine", "Steam inhalation"],
    "Pneumonia": ["Amoxicillin", "Clarithromycin", "Ceftriaxone"],
    "Dimorphic hemorrhoids": ["Sitz bath", "Fiber diet", "Hydrocortisone cream"],
    "Heart attack": ["Aspirin", "Clopidogrel", "Emergency care"],
    "Varicose veins": ["Compression", "Elevation", "Surgery if severe"],
    "Hypothyroidism": ["Levothyroxine", "Regular monitoring", "Iodine"],
    "Hyperthyroidism": ["Methimazole", "Radioactive iodine", "Surgery"],
    "Hypoglycemia": ["Glucose", "Dextrose IV", "Glucagon"],
}

def get_medicines(disease):
    for key in MEDICINES:
        if key.lower() == disease.lower():
            return MEDICINES[key]
    return ["Please consult a doctor for medication advice."]